x-treatment-base-app: &base
  restart: on-failure
  networks:
    - backend-net
  logging:
    driver: journald
    options:
      tag: "{{.Name}}"

x-treatment-django-app: &backend
  <<: *base
  build: .
  env_file:
    - "envs/.env.${DJANGO_ENV:-local}"
  volumes:
    - media_data:/app/media
    - static_data:/app/static
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  backend:
    container_name: backend
    <<: *backend
    ports:
      - 8000:8000

  postgres:
    <<: *base
    image: postgres:16.3-alpine3.20
    container_name: postgres
    environment:
      POSTGRES_DB: appstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5

  redis:
    <<: *base
    image: redis:7.2-alpine3.20
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s


volumes:
  postgres_data:
  media_data:
  static_data:

networks:
  backend-net:
