#!/bin/bash

THERE_IS_NO_CONFIGURATION_FILE='There is no configuration file.'
SELECTED_PATH=$(pwd)/$1
WALKED_DIR=$(pwd)

print_message () {
  printf "\033[1;%sm%s\033[0m\n" "$1" "$2"
}

while [ "$WALKED_DIR" ]
do
  if [ -f ./pyproject.toml ];
    then break;
  elif [ "$WALKED_DIR" == "/" ]
    then print_message "31" "$THERE_IS_NO_CONFIGURATION_FILE";
    exit 1;
  else
    cd .. && WALKED_DIR=$(pwd);
  fi
done

ruff format; ruff check;
